springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /form-modeler/v3/api-docs


gateway:
  uri: ${GATEWAY_URI}
keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/
database:
  url: ${tp_modeler_app_mongoUri}
  name: techsophy-platform

opentracing:
  spring:
    cloud:
      log:
        enabled: true
