spring:
  data:
    mongodb:
      uri: ${PCIL_MONGO_URI}
      
springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /pcil-erp-sync/v3/api-docs
      
keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/
  
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        evenrConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
