spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

dms:
  s3:
    bucket: ${AWS_BUCKET_NAME}
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}

keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/

database:
  url: ${TP_MODELER_APP_MONGO_URI}
  name: techsophy-platform

gateway:
  uri: ${GATEWAY_URI}

springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /dms/v3/api-docs

default:
  pagelimit: 5
