spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER_URL}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

dms:
  s3:
    enabled : false
    bucket: ${AWS_BUCKET_NAME}
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    endpoint: ${AWS_ENDPOINT}


keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/

database:
  url: ${TP_MODELER_APP_MONGO_URI}
  name: techsophy-platform

gateway:
  uri: ${GATEWAY_URI}


default:
  pagelimit: 5


springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /dms/v3/api-docs



elasticsearch:
  uri: ${ELASTIC_SEARCH_URL}
  enable: false


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG