spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/${KEYCLOAK_REALM_NAME}


gateway:
  uri: ${GATEWAY_URI}

camunda-engine.servlet.context-path : ${CAMUNDA_ENGINE_CONTEXT_PATH}

springdoc:
  api-docs:
    path: workflow/v3/api-docs
