spring:
  application:
    name: tp-app-notification
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 100
    exception-handlers-enabled: false
    mapping: /notification/v1/graphql
  playground:
    enabled: true

voyager:
  enabled: true

notification:
  aws:
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY}
    access-secret: ${AWS_ACCESS_SECRET}
  sns:
    access-key: ${SNS_ACCESS_KEY}
    secret-key: ${SNS_SECRET_KEY}
    region: ${SNS_REGION}
    arn: ${SNS_TOPIC_ARN}
  db:
    provider:
      mongodb:
        enabled: ${DB_MONGO_ENABLED:true}
      memory:
        enabled: ${DB_MEMORY_ENABLED:false}
  sms:
    enabled: ${SMS_ENABLED:true}
    provider:
      twilio: ${SMS_PROVIDER_TWILIO:false}
      aws: ${SMS_PROVIDER_AWS:true}
  email:
    enabled: ${EMAIL_ENABLED:true}
    provider:
      sendMail: ${EMAIL_PROVIDER_SENDMAIL:true}
      sendGrid: ${EMAIL_PROVIDER_SENDGRID:false}
      awsSES: ${EMAIL_PROVIDER_AWS_SES:false}
  firebase:
    enabled: ${FIREBASE_ENABLED:false}
    app: ${FIREBASE_APP}
  smtp:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    user: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    debug: false
  templates:
    enabled: ${TEMPLATES_ENABLED}
  dms:
    enabled: ${DMS_ENABLED}
  twilio:
    accountId: ${TWILIO_ACCOUNT_ID}
    token: ${TWILIO_TOKEN}
    msId: ${TWILIO_MSID}




elasticsearch:
  enabled: ${ELASTIC_SEARCH_ENABLED:false}
  host: ${ELASTIC_SEARCH_HOST}

database:
  url: ${TP_MODELER_APP_MONGO_URI}
  name: techsophy-platform

gateway:
  uri: ${GATEWAY_URI}

keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/







