spring:
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
database:
  url: ${TP_MODELER_APP_MONGO_URI}
  name: techsophy-platform
keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/


springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /template-modeler/v3/api-docs

default:
  pagelimit: 20