spring:
  application:
    name: account-app

keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/
database:
  url: ${TP_MODELER_APP_MONGO_URI}
  name: techsophy-platform

user:
  management:
    keycloak-api: ${KEYCLOAK_URL_AUTH}/auth/admin/realms/
    user-api: /users
    roles-api: /roles
    groups-api: /groups
    count-api: /count

default:
  pagelimit: 5

gateway:
  uri: ${GATEWAY_URI}

springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /accounts/v3/api-docs

email:
  validity: ${EMAIL_VALIDITY:86400}
otp:
  validity: ${OTP_VALIDITY:180}
USER:
  REGISTRATION:
    FAILURE:
      EMAIL:
        TO: ${USER_REGISTRATION_FAILURE_EMAIL_TO}
        SUBJECT: ${USER_REGISTRATION_FAILURE_EMAIL_SUBJECT}


notification:
  enabled: true
  email:
    query: "mutation SEND_EMAIL($mailMessage: MailMessage!) {\n  sendMail(input: $mailMessage)\n}\n"
  sms:
    query: "mutation SEND_SMS($smsMessage: smsMessage!) {\n  sendSMS(input: $smsMessage)\n}\n"



