spring:
  application:
    name: deployment-app
    package-location: ${DEPLOYMENT_TMP_DIR}


keycloak:
  issuer-uri: ${KEYCLOAK_URL_AUTH}/auth/realms/


database:
  url: ${tp_modeler_app_mongoUri}
  name: techsophy-platform

gateway:
  uri: ${GATEWAY_URI}

modelers:
  deployment:
    forms-api: /form-modeler/v1/forms/
    workflows-api: /process-modeler/v1/processes/
    rules-api: /rule-modeler/v1/rules/

springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /deployment/v3/api-docs